### ISSUE TITLE
FSE Application - FSE Report - Remove Database IDs

### ISSUE THREAD

**Issue by JMurk** [JMurk/FSE_Application_Issues#13]
Issue:  The database IDs (GCD ID, FSE INSPECTION ID, and GCD INSPECTION ID) are causing confusion among the users.  The should be removed from the report.

Resolution:  Please removed the database IDs listed above from the report.

**Comment by tarheelgis** [comment]
What would we use as the identifier for each GCD other than GCD ID then?

**Comment by JMurk** [comment]
I'm not sure... Does it absolutely need the ID?  Could it just say some thing like "Expand to View Inspection/GCD"?  Or maybe we can use date?

**Comment by tarheelgis** [comment]
I would think it just needs some sort of unique identifier. Either per GCD (GCD_ID) or desciptor ("The GCD in the back on the left"), because in the case where a users wishes to locate the history of one FSE that has multiple GCD's the user will not know which GCD they are looking at or looked at in the past. They will just have what would appear to be random GCD inspections unassociated with no one particular GCD.

**Comment by JMurk** [comment]
I think we can leave the GCDID for that purpose.
